### PR TITLE
Ltm policy datagroup filtering

### PR DESCRIPTION
**Pull request by diaconud007**
this solve issue #706

### CODE REVIEW

**Comment by RavinderReddyF5** [comment]
@diaconud007 Thanks for PR, can you please submit CLA.

https://github.com/F5Networks/terraform-provider-bigip/blob/master/F5_Contributor_License_Agreement.pdf

**Comment by diaconud007** [comment]
@RavinderReddyF5 signed and sent. Thank you!

**Comment by diaconud007** [comment]
@RavinderReddyF5 hi. any news about the merging of this PR? thank you!

**Comment by RavinderReddyF5** [comment]
@diaconud007 reviewing with internal JIRA, will be merged with release.

**Pull request merged**
