### PR TITLE
Terraform Lint for docs and acceptance tests

### PR DESCRIPTION
**Pull request by AliAllomani**
* TF Lint scripts via `make tflint` and `make tffmtfix`
* github action to test tf lint on PRs
* fixing the current lint issues in docs and acceptance tests

### CODE REVIEW

**Comment by RavinderReddyF5** [comment]
@AliAllomani thanks for PR, will review file changes and merge PR

**Comment by RavinderReddyF5** [comment]
@AliAllomani are you looking into other PR failures?

**Comment by AliAllomani** [comment]
> @AliAllomani are you looking into other PR failures?

@RavinderReddyF5  if you mean #540, you can ignore these failures now and merge, i will fix them in phase 2 of lint fix as they need some functional code changes so i prefer to do it in a separate PR

**Comment by RavinderReddyF5** [comment]
@AliAllomani thanks for your input and contribution, we also internally looking and  working for fixing these PR Merge failures

**Comment by RavinderReddyF5** [comment]
looks good.

**Pull request merged**
