### PR TITLE
Go Lint fixes / Phase 2

### PR DESCRIPTION
**Pull request by AliAllomani**
Fixing the remaining go lint issues.

### CODE REVIEW

**Comment by AliAllomani** [comment]
@RavinderReddyF5 do you have some time to check this PR? this is related to #540

**Comment by RavinderReddyF5** [comment]
@AliAllomani thanks for your PR, yes we are tracking this Internally, and will make sure this goes with coming release.

**Comment by RavinderReddyF5** [comment]
@AliAllomani do we need consider PR : https://github.com/F5Networks/terraform-provider-bigip/pull/541 as well ?

**Comment by RavinderReddyF5** [comment]
@AliAllomani because same file changed through both PRs, i believe it give merge conflicts, please let us know

**Comment by AliAllomani** [comment]
@RavinderReddyF5 it doesn’t show merge conflicts on my side, however you can merge this one and then i will resolve the conflicts in #541 if needed.

#541 is for terraform code lint, this one is for go code lint

**Comment by RavinderReddyF5** [comment]
@AliAllomani sorry it is with PR : https://github.com/F5Networks/terraform-provider-bigip/pull/540, and i see conflicts with file : bigip/validators.go, verifying some testing from my side before merging.

**Comment by RavinderReddyF5** [comment]
Looks good

**Pull request merged**
