### PR TITLE
fix for #148

### PR DESCRIPTION
**Pull request by scshitole**
```

=== RUN   TestAccBigipLtmNode_create
--- PASS: TestAccBigipLtmNode_create (6.09s)
=== RUN   TestAccBigipLtmNode_import
--- PASS: TestAccBigipLtmNode_import (6.05s)
=== RUN   TestAccBigipLtmNodeInvalid
--- PASS: TestAccBigipLtmNodeInvalid (0.01s)
=== RUN   TestAccBigipLtmNodeCreate
--- PASS: TestAccBigipLtmNodeCreate (0.06s)
```

### CODE REVIEW

**Comment by scshitole** [comment]
@dannyk81 @jlosito can you please review

**Comment by dannyk81** [comment]
@scshitole thanks for this fix, however you merged this before we had the chance to go over it.

so here are my comments:
1. This attribute shouldn't have a Default defined, it is not needed and just creates confusion. Description defaults to an empty string anyway. 

2. you only fixed Node resource, same fixes required  in the VS and Pool resources.

**Comment by RavinderReddyF5** [comment]
Hi @scshitole @dannyk81 @jlosito 

please review Changes for Description issue fix for Pool and Virtual Server.
https://github.com/terraform-providers/terraform-provider-bigip/pull/151

**Comment by dannyk81** [comment]
Left some comments in #151, thanks!

**Pull request merged**
