### PR TITLE
added core c3d capability

### PR DESCRIPTION
**Pull request by darkedges**
This provide c3d capability to the plugin.

it has a dependency on this pull request https://github.com/f5devcentral/go-bigip/pull/59

Happy to work on any improvements required.

### CODE REVIEW

**Comment by darkedges** [comment]
Will work on the merge issues.

**Comment by RavinderReddyF5** [comment]
@darkedges Thanks for your PR, Can you please complete : https://github.com/F5Networks/terraform-provider-bigip#f5-networks-contributor-license-agreement

**Comment by darkedges** [comment]
Screenshot_20210317-182726
Agreement sent.

**Comment by nmenant** [comment]
Our apologies for this. This should be fixed now. Could you send your email again ? Thanks

**Comment by darkedges** [comment]
Thanks. Have submitted were mentioned.

**Comment by nmenant** [comment]
We've received your CLA but It seems like you forgot to sign it. Could you sign it and send it again ? Thanks for your support

**Comment by darkedges** [comment]
Resent

**Pull request merged**
