### PR TITLE
Incorrect 'bigip_ltm_monitor' parent profile name validation for tcp_half_open

### LINKED ISSUE #690: Incorrect 'bigip_ltm_monitor' parent profile name validation for tcp_half_open
### Environment

 * TMOS/Bigip Version: BIG-IP 16.1.3 Build 0.0.12 Final
 * Terraform Version: 1.2.7
 * Terraform bigip provider Version: 1.15.1

### Summary

Get the following error when trying to create an ltm monitor with tcp_half_open as the parent profile:

`parent must be one of /Common/udp, /Common/postgresql, /Common/mysql,/Common/mssql, /Common/http, /Common/https, /Common/icmp, /Common/gateway_icmp, /Common/tcp-half-open, /Common/tcp, /Common/ftp`

The parent profile is actually tcp_half_open and not tcp-half-open

This is similar to https://github.com/F5Networks/terraform-provider-bigip/issues/553 but for another monitor type.

### Steps To Reproduce

1. Just create a big_ltm_monitor resource using the parent tcp-half-open:

`resource "bigip_ltm_monitor" "potential-provider-bug" {
  name        = "/Common/potential-bug"
  parent      = "/Common/tcp-half-open"
  timeout     = "16"
  interval    = "5"
  destination = "10.10.10.10:1234"
}`

3. Using tcp-half-open as the parent returns the following error:

`Error: HTTP 400 :: {"code":400,"message":"01070043:3: Monitor /Common/potential-provider-bug parent not found.","errorStack":[],"apiError":3}`

### PR DESCRIPTION
**Pull request by steven-visagie**
Fixes #690
* Correcting URI for tcp_half_open monitor.
* Adding testcase for the change.

### CODE REVIEW

**Comment by RavinderReddyF5** [comment]
@steven-visagie thank your PR, Can you please do [CLA](https://github.com/F5Networks/terraform-provider-bigip/blob/master/F5_Contributor_License_Agreement.pdf)

**Comment by steven-visagie** [comment]
> @steven-visagie thank your PR, Can you please do [CLA](https://github.com/F5Networks/terraform-provider-bigip/blob/master/F5_Contributor_License_Agreement.pdf)

Have completed and mailed as instructed.

**Comment by RavinderReddyF5** [comment]
@steven-visagie created Internal Story for PR review: INFRAANO-877

**Comment by RavinderReddyF5** [comment]
LGTM

**Pull request merged**
