### PR TITLE
add smtp to parentMonitors

### PR DESCRIPTION
**Pull request by idrissae**
hello F5
I added smtp monitor to the list of supported LTM monitors by the actual version
could you please accept this pull request.
I note that ,also,  the the API Client github.com/f5devcentral/go-bigip need a modification, I will send also a Pull request
please let me know if you have a question
thank you

### CODE REVIEW

**Review by netdev-iae — APPROVED** [review]
its seems good

**Review by netdev-iae — CHANGES_REQUESTED** [review]
its okey

**Comment by RavinderReddyF5** [comment]
HI @idrissae thanks for your PR, please make go-bigip changes as part of vendor folder and can you please submit  [CLA](https://github.com/F5Networks/terraform-provider-bigip/blob/master/F5_Contributor_License_Agreement.pdf).

**Comment by idrissae** [comment]
hello RavinderReddyF5
thank you for your replay
I sent the PR in go-bigip, also please find the signed CLA attached to this
email
thank you

**Review by RavinderReddyF5 — APPROVED** [review]
Changes LGTM

**Pull request merged**
