### PR TITLE
Go Lint fixes / Phase 1

### PR DESCRIPTION
**Pull request by AliAllomani**
Fixing lint issue for go

Phase 1: 

* General code cleanup
*  removed un-used code
* fixed comments spaces
* simplify if functions
* fix mis-spelled words

Phase 2 will be in separate PR to fix functional errors and error code check.

### CODE REVIEW

**Comment by RavinderReddyF5** [comment]
@AliAllomani thanks for PR, will review file changes and merge PR

**Comment by papineni87** [comment]
@AliAllomani  why build failure not showing up the details on where it failed ? any idea ?

**Comment by AliAllomani** [comment]
> @AliAllomani why build failure not showing up the details on where it failed ? any idea ?

@papineni87 do you mean the lint job? they appear in the job log

https://github.com/F5Networks/terraform-provider-bigip/runs/3282644230?check_suite_focus=true

they also appear in PR files

https://github.com/F5Networks/terraform-provider-bigip/pull/540/files

**Comment by AliAllomani** [comment]
failures from lint job can be ignored for this PR as there are still issues to be fixed in phase 2

**Comment by RavinderReddyF5** [comment]
@AliAllomani thanks for confirmation, will be merging this PR.

**Pull request merged**
